begin tran
UPDATE documentos..plantilla_configuracion
SET    consulta=   'SELECT CASE pe.id_tipo_identificacion WHEN ''2'' THEN pj.nombre_comercial ELSE UPPER(CONCAT (pe.nombre1,'' '',pe.nombre2,'' '',pe.apellido1,'' '',pe.apellido2)) END as nombreCompleto,  pr.numero_proceso, tip.codigo, pe.numero_identificacion, pr.fecha_inicio, year(pr.fecha_inicio) as anio_proceso, c.fecha_infraccion,    c.hora_infraccion, CASE i.numeral_infraccion WHEN '' '' THEN CONCAT(''Articulo '',ci.articulo,'' - '',nm.nombre) ELSE CONCAT(''Articulo '',ci.articulo,'', numeral '',i.numeral_infraccion,'' - '',nm.nombre) END as infraccion,    ci.descripcion,   mp.descripcion_hechos,   eimp.consideracion_juridica,   ec.nombre,   c.numero_citacion,   tpf.id_trazabilidad_proceso,  cv.placa_vehiculo,  fu.memo_nombramiento,  fu.fecha_nombramiento,   CONCAT(per.nombre1,'' '',per.nombre2,'' '',per.apellido1,'' '',per.apellido2) AS nombreAbogadoFirma,  car.nombre AS NombreCargo,   (SELECT MAX(numero_imagen) FROM firma_persona fpe (NOLOCK) WHERE fpe.id_persona = per.id_persona) as Firma,   (SELECT TOP 1 cp.correo_electronico FROM correo_persona cp (NOLOCK) WHERE cp.estado = 1 AND cp.id_persona = pe.id_persona ORDER BY cp.fecha_registro DESC) AS correos  
TEXTO_NOMBRE_2,

(select TOP 1 CONCAT(f.titulo_obtenido, '' '', p.nombre1, '' '', p.nombre2, '' '', 
p.apellido1, '' '', p.apellido2) 
from funcionario f
join persona p on f.id_persona=p.id_persona
where id_cargo=11 
and fecha_final_vigencia is null) AS nombreDirector

FROM proceso pr (NOLOCK)   JOIN comparendo_proceso cp (NOLOCK) ON cp.id_proceso = pr.id_proceso    JOIN comparendo c (NOLOCK) ON cp.cicomparendo = c.cicomparendo    LEFT JOIN comparendo_vehiculo cv (NOLOCK) ON cv.id_comparendo_vehiculo=c.cicomparendo    JOIN estado_comparendo ec (NOLOCK) ON ec.id_estado_comparendo = c.id_estado_comparendo    JOIN infraccion i (NOLOCK) ON c.id_infraccion = i.id_infraccion    JOIN configuracion_infraccion ci (NOLOCK) ON ci.id_infraccion = i.id_infraccion AND ci.fecha_fin_vigencia IS NULL    JOIN normatividad nm (NOLOCK) ON nm.id_normatividad = ci.id_normatividad    JOIN participante_proceso pp (NOLOCK) ON pp.id_proceso = pr.id_proceso AND pp.id_tipo_participante = 2    JOIN persona pe (NOLOCK) ON pp.id_persona = pe.id_persona    LEFT JOIN persona_juridica pj (NOLOCK) ON pj.id_persona_juridica = pe.id_persona    JOIN tipo_identificacion_persona tip (NOLOCK) ON pe.id_tipo_identificacion = tip.id_tipo_identificacion    JOIN trazabilidad_proceso tp (NOLOCK) ON tp.id_proceso = pr.id_proceso    JOIN trazabilidad_proceso tpf (NOLOCK) ON tpf.id_proceso = pr.id_proceso    JOIN motivacion_impugnacion mp (NOLOCK) ON mp.id_trazabilidad_proceso = tp.id_trazabilidad_proceso    LEFT JOIN evaluar_impugnacion eimp (NOLOCK) ON eimp.id_trazabilidad_proceso = tpf.id_trazabilidad_proceso    JOIN funcionario fu (NOLOCK) ON fu.id_funcionario = (SELECT ei.id_funcionario FROM evaluar_impugnacion ei  INNER JOIN trazabilidad_proceso tp ON tp.id_trazabilidad_proceso = ei.id_trazabilidad_proceso WHERE tp.id_proceso = pr.id_proceso)   JOIN cargo car (NOLOCK) ON car.id_cargo = fu.id_cargo   JOIN persona per (NOLOCK) ON per.id_persona = fu.id_persona   WHERE pr.id_proceso = :idProceso order by tpf.id_trazabilidad_proceso desc'               
	   , orden_variables='NOMBRE_INFRACTOR,numero_consecutivo,T_DOCUMENTO_INFRACTOR,DOCUMENTO_INFRACTOR,fecha_apertura_impug,anio_apertura_proceso,FECHA_IMPOSICION_COMPARENDO,HORA_IMPOSICION_COMPARENDO,ARTICULO,DESCRIPCION_INFRACCION,desc_motivacion,consi_juridica,ESTADO_CITACION,numero_citacion,orden,PLACA_VEHICULO,MEMO_DELEGADO,FECHA_DELEGADO,NOMBRE_DELEGADO,CARGO_DELEGADO,IMAGEN_FIRMA,CORREO_ELECTRONICO_INFRACTOR,TEXTO_NOMBRE_2'
WHERE  id_plantilla_config=10186

commit tran